_redirects

Redirect alias to primary domain

---

docusaurus.config.js
src/pages/docs.js

* Add custom code styles
* Small UI fixes to docs page
Cleaning up UI

Rebranding Updates

---

docusaurus.config.js
src/css/custom.css
src/pages/docs.js

Fix line highlighting in light and dark mode

Rebranding

---

docs/CONTRIBUTING.md

Using admonitions in place of callouts.
Admonitions provide a clearer way to bring attention to specific context or provide context.

Replace callouts with admonitions

---

docusaurus.config.js

Enable editUrl for more casual/direct contributions.
Should be easy to contribute for someone making small contributions.

Enable editUrl

---

src/css/custom.css

Removed erroneous CSS and added appropriate surface background colors.

Fix bg surface color for light/dark mode

---

docusaurus.config.js

Switch to free docsearch 
Allows us to cancel our paid. pro plan.

Switch to docsearch

---

docs/CONTRIBUTING.md

Updating git URLs
Git URLs should use SSH instead of HTTPS
Previewed locally

Updating git URLs

---

src/css/custom.css

hide dropdown caret on mobile navbar menu
Improves UX
locally and CI/CD

Hide dropdown caret on mobile

---

src/css/custom.css
src/theme/Navbar/index.js
yarn.lock

fixed dropdown

---

docusaurus.config.js
src/components/docsHome.js

Add Expedition to docbar and dochome
Provide seamless way for users to navigate to and from Expedition content.
local dev server

Update doc home

---

docs/expedition/expedition_apiInt.md
docs/expedition/expedition_qs.md
docs/expedition/workflow.md
docs/expedition/workflow.mdx
sidebars.js

Modify Expedition_apiint.md to includes more contents
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.

{modify expedition/expedition_apiint.md]

---

docs/expedition/expedition_apiInt.md
docs/expedition/expedition_qs.md
docs/expedition/workflow.md
docs/expedition/workflow.mdx
sidebars.js

Add Coding selections in workflow.mdx file
New feature added so user can select bewteen different coding language. 
Tested it in local web server
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.

Add Coding selections in workflow.mdx file

---

src/pages/index.js

Adding Expedition to feature section to improve visibility.
Visitors tend to stick to top of the home page when first visiting.
Local dev instance and Netlify.

Add Expedition to feature section

---

docs/expedition.md
docs/expedition/expedition_apiInt.md
docs/expedition/expedition_qs.md

Fix typo and add software update commands
Fix typo and add new content
Test is in local docsaura 
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.

Fix typo and add software update commands

---

docs/expedition.md
docs/expedition/expedition_apiInt.md
docs/expedition/expedition_qs.md

Changing checkmark in vendor matrix , so it can be shown in darkmode
Suggestion from user
Yes, tested in local 
- [ x] I have updated the documentation accordingly.

fixing vendor matrix in darkmode

---

docs/automation/ansible_qs.md

Update Ansible collection repo, documentation, examples repo

Update Ansible docs

---

docs/apis/xmlapi_qs.md

I've created a [Postman collection](https://documenter.getpostman.com/view/2937330/7LgDQwG) to better document the XML-API and make running examples easier.

Link to Postman collection

---

.idea/.gitignore
.idea/codeStyles/codeStyleConfig.xml
.idea/misc.xml
.idea/modules.xml
.idea/templateLanguages.xml
.idea/vcs.xml
panos.pan.dev.iml

Cleaning up files added unintentionally.
Early spring cleaning.
local dev server and Netlify

Cleanup non-essential files

---

docs/expedition/expedition_export.md

Modified Export configuration page for Stonesoft and  SonicWall 
Adding more export config instructions for Stonesoft and  SonicWall
X New feature (non-breaking change which adds functionality)
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.

modified export instruction page

---

docs/automation.md
docs/automation/terraformer_qs.md
sidebars.js
src/components/docsHome.js

Add Terraformer documentation.
```sh
$ yarn start
```

feat: add documentation about Terraformer

---

static/oas/iot/iot.yaml

IoT: Device bulkupdate API

---

docs/expedition.md
docs/expedition/expedition_apiInt.md
docs/expedition/expedition_contact.md
docs/expedition/expedition_qs.md

Adding Banner to inform user about Expedition 2.x release date
So user won't testing Expedition 2.x until further notice. 
x New feature (non-breaking change which adds functionality)
- [ x] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.

Adding Banner on Expedition 2.x pages to inform users about release date.

---

static/oas/iot/api/public/tagList.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

documentation for tags addition to public apis

---

static/oas/iot/api/public/alertList.yaml
static/oas/iot/api/public/deviceDetail.yaml
static/oas/iot/api/public/tagList.yaml

text xhanges as suggested by Joe and a bug

---

docs/expedition/expedition_export.md

Add checkpoint tool version in the checkpoint configuration export instructions
suggested by user
testing viewing on local 
New feature (non-breaking change which adds functionality)
- [ x] I have added tests to cover my changes if appropriate.
- x[ ] All new and existing tests passed.

added version info on checkpoint tool

---

static/oas/iot/api/public/bulkUpdate.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

BAN-6566 delete deviceType from CISCO WLC, delete updateSource from DNAC and Prime

---

static/oas/iot/api/public/bulkUpdateCellular.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

Adding Cellular bulkUpdate api and changed several wordings

---

static/oas/iot/api/public/deviceDetailPerIP.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

BAN-6315: IOT api device detail per IP

---

static/oas/iot/api/public/alertList.yaml
static/oas/iot/api/public/deviceList.yaml
static/oas/iot/api/public/vulnerabilityList.yaml

BAN-7016 Updating public api doc

---

docs/expedition.md

Remove sonicwall and vpn feature on juniper from the supported vendor matrix 
Because the vendor is not supported yet. 
Tested it at local 
x- Bug fix (non-breaking change which fixes an issue)
- [x ] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.

Remove unsupported features in the vendor supported matrix

---

docs/expedition/expedition_apiInt.md
docs/expedition/expedition_contact.md
docs/expedition/expedition_qs.md

Update Release date
Release date has been changed. 
- [x ] I have read the **CONTRIBUTING** document.

Update Expedition 2.x new release date

---

static/oas/iot/api/public/profileMapping.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

To add a new IoT public API "profile mapping"

BAN-7252 IoT public API - profile mapping

---

static/oas/iot/components/schemas.yaml

BAN-7252 Remove api & ver from response schema

---

static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml

IoT API: remove removed field for pr

---

static/oas/iot/components/examples.yaml

remove unknown applications

---

static/oas/iot/api/public/bulkUpdateCrowdstrike.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

BAN-8384-add_crowdstrike_config

---

static/oas/iot/api/public/bulkUpdateCrowdstrike.yaml
static/oas/iot/api/public/bulkUpdateSccm.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

BAN-7629-add_sccm_bulkUpdate

---

static/oas/iot/api/public/alertList.yaml
static/oas/iot/api/public/alertResolve.yaml
static/oas/iot/api/public/bulkUpdate.yaml
static/oas/iot/api/public/bulkUpdateArubaWLC.yaml
static/oas/iot/api/public/bulkUpdateCellular.yaml
static/oas/iot/api/public/bulkUpdateCiscoWLC.yaml
static/oas/iot/api/public/bulkUpdateSNMP.yaml
static/oas/iot/api/public/deviceDetail.yaml
static/oas/iot/api/public/deviceDetailPerIP.yaml
static/oas/iot/api/public/deviceList.yaml
static/oas/iot/api/public/policyRecommendation.yaml
static/oas/iot/api/public/profileMapping.yaml
static/oas/iot/api/public/tagList.yaml
static/oas/iot/api/public/vulnerabilityList.yaml
static/oas/iot/api/public/vulnerabilityResolve.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

IoT public API document update

---

static/oas/iot/api/public/bulkUpdateIPAMSubnet.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

We are adding a new public API to store and update subnets learned from customer IPAM.
The API is "put".
Brand new API Documentation for our internal and external customer.
Unit tests,
Integration Tests
End To End Testing by QA team.
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.

Documentation for the IPAM Bulk update Public API

---

static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml

Ban-9145 update some descriptions

---

static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

BAN-9145 Adding more details

---

static/oas/iot/api/public/alertVuln.yaml
static/oas/iot/components/examples.yaml
static/oas/iot/components/schemas.yaml
static/oas/iot/iot.yaml

BAN-9116 Adding alert vuln capability public api

---

static/oas/iot/components/schemas.yaml

Detailed context could be found in
https://zingbox.atlassian.net/browse/BAN-8753?filter=-1
We need to update api docs after change

add profile_vertical field into alert details

---

firebase.json

add redirects for pan.dev migration
